In [ ]:
x = 0
while not (1 <= x <= 200):
    x = int(input("Please enter a value between 1 and 200: "))
    print("Valid number:", x)
    


In [ ]:
for i in range(4):
    x = int(input("Please enter a value between 50 and 100: "))
    if 50 <= x <= 100:
        print("Valid number:", x)
        break
    else:
        print("Invalid number, try again.")


In [ ]:
set1={1,2,100,"ram","mango"}
print(set1)
print(type(set1))

{1, 2, 100, 'ram', 'mango'}
<class 'set'>


In [ ]:
set2={}
print(type(set2))

<class 'dict'>


In [ ]:
set2=()
print(type(set2))

<class 'tuple'>


In [ ]:
set2=set()
print(type(set2))

<class 'set'>


In [ ]:
set1={1,2,3,100}
set1.remove(100)
set1.discard(1)
print(set1)

{2, 3}


In [ ]:
set1={1,2,3,100}
set1.add(200)
print(set1)

{1, 2, 3, 100, 200}


In [ ]:
my_list=[1,4,6,7,4]
my_list[3]

7

In [ ]:
my_list=[1,4,6,7,4]
my_list[-3]

6

In [ ]:
my_list=[[1,2,3,4],"ram",[4,5,6]]
my_list[2][2]

6

In [ ]:
my_list=[[1,2,3],[["a","b","c"],5,6]]
my_list[1][1]

5

In [ ]:
language=["c","c++","java"]
language.append("php")
language

['c', 'c++', 'java', 'php']

In [ ]:
language=["c","c++","java"]
language.append("php")
language.append("oop")
language

['c', 'c++', 'java', 'php', 'oop']

In [ ]:
language=["c","c++","java"]
language.append(["JS","NOTE"])
language.append("php")
language

['c', 'c++', 'java', ['JS', 'NOTE'], 'php']

In [ ]:
language=["c","c++","java"]
language.insert(1,"php")
language

['c', 'php', 'c++', 'java']

In [ ]:
fruits=["apple","banana"]
games=["ludo","chess"]
fruits.extend(games)
fruits

['apple', 'banana', 'ludo', 'chess']

In [ ]:
name =input()
print(name)

In [ ]:
num =int( input ("enter a number"))

In [ ]:
for i in range (0,2):
    print("hello world")

hello world
hello world


In [ ]:
sentence ="i am a student"
sentence.split()

['i', 'am', 'a', 'student']

In [ ]:
fruits= ("mango","banana","graphs")
fruits
fruits(2)

TypeError: 'tuple' object is not callable

In [ ]:
cars=("audi")
cars

'audi'

In [1]:
import numpy as np

In [7]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8,9])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8 9]


In [ ]:

np.size(b)

5

In [9]:
np.ndim(a)

1

In [10]:
np.shape(a)

(4,)

In [11]:
a=np.array([1,2,3,5,10,12,15])
print(a)

[ 1  2  3  5 10 12 15]


In [13]:
a=np.arange(5,10)
print(a)

[5 6 7 8 9]


In [14]:
a=np.arange(0,1,0.2)
print(a)

[0.  0.2 0.4 0.6 0.8]


In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [24]:
np.linspace(0,1,num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [25]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [26]:
np.random.randn(2,2)

array([[ 1.03669171, -0.39035366],
       [ 0.64957808,  0.07235828]])

In [27]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]
